plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
  base    = "flutter_app"
  publish = "flutter_app/build/web"
  command = "flutter build web --release --dart-define=API_BASE_URL=$API_BASE_URL"

[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]