# netlify.toml

[build]
  base    = "flutter_app"
  publish = "flutter_app/build/web"
  command = "flutter pub get && flutter build web --release --dart-define=API_BASE_URL=https://vitalrack-backend.onrender.com"

# Todas las rutas deben resolverse a index.html (SPA)
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
