name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  backend:
    name: Backend Tests
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:5.0
        ports: ['27017:27017']
    
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run backend tests
        run: npm test

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: coverage-backend
          path: coverage/

  flutter:
    name: Flutter Analyze & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'     # <-- especificamos versión concreta

      - name: Cache Flutter packages
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('flutter_app/pubspec.lock') }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_app

      - name: Analyze
        run: flutter analyze
        working-directory: flutter_app

      - name: Run Flutter tests
        run: flutter test --coverage
        working-directory: flutter_app

  deploy-flutter-web:
    name: Deploy Flutter Web to Netlify
    needs: flutter
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'

      - name: Install & build web
        run: |
          flutter pub get
          flutter build web --release
        working-directory: flutter_app

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID:   ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify link --id $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
          netlify deploy --prod --dir=flutter_app/build/web
