# .github/workflows/flutter-ci.yml
name: Flutter CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_app
      - name: Run analyze
        run: flutter analyze --no-fatal-infos --no-fatal-warnings
        working-directory: flutter_app

  test:
    name: Flutter Tests
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.6'
      - name: Install dependencies
        run: flutter pub get
        working-directory: flutter_app
      - name: Run tests
        run: flutter test --coverage
        working-directory: flutter_app
      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: flutter-coverage
          path: flutter_app/coverage
