name: Flutter CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.10.6' }
      - run: flutter pub get
        working-directory: ./flutter_app
      - run: flutter analyze --no-fatal-infos --no-fatal-warnings
        working-directory: ./flutter_app

  test:
    name: Flutter Tests
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with: { flutter-version: '3.10.6' }
      - run: flutter pub get
        working-directory: ./flutter_app
      - run: flutter test --coverage
        working-directory: ./flutter_app
      - uses: actions/upload-artifact@v3
        with:
          name: flutter-coverage
          path: flutter_app/coverage
